import { Job, StaffMember } from './types';

export const COUNTRIES: { id: string, name: Record<string, string> }[] = [
  { id: 'all', name: { bn: 'সকল চাহিদা', en: 'All Demands', ar: 'كل الطلبات' } },
  { id: 'saudi', name: { bn: 'সৌদি আরব', en: 'Saudi Arabia', ar: 'المملكة العربية السعودية' } },
  { id: 'qatar', name: { bn: 'কাতার', en: 'Qatar', ar: 'قطر' } },
  { id: 'malaysia', name: { bn: 'মালয়েশিয়া', en: 'Malaysia', ar: 'ماليزيا' } },
  { id: 'japan', name: { bn: 'জাপান', en: 'Japan', ar: 'اليابان' } },
];

export const JOB_DEMANDS: Job[] = [
  {
    role: { bn: 'সিটি ক্লিনার', en: 'City Cleaner', ar: 'عامل نظافة مدينة' },
    company: { bn: 'আল ফাহাদ কোং', en: 'Al Fahad Co.', ar: 'شركة الفهد' },
    destination: { bn: 'সৌদি আরব', en: 'Saudi Arabia', ar: 'المملكة العربية السعودية' },
    quantity: 50,
    salary: { bn: '৮০০+২০০ SAR + থাকা', en: '800+200 SAR + Accommodation', ar: '٨٠٠+٢٠٠ ريال سعودي + سكن' },
    imageUrl: 'https://i.imgur.com/LWAbD7e.jpeg',
  },
  {
    role: { bn: 'সিটি ক্লিনার', en: 'City Cleaner', ar: 'عامل نظافة مدينة' },
    company: { bn: 'আল হুকামা কোম্পানী', en: 'Al Hukama Company', ar: 'شركة الحكماء' },
    destination: { bn: 'সৌদি আরব', en: 'Saudi Arabia', ar: 'المملكة العربية السعودية' },
    quantity: 50,
    salary: { bn: '৮০০+২০০ SAR + থাকা', en: '800+200 SAR + Accommodation', ar: '٨٠٠+٢٠٠ ريال سعودي + سكن' },
    imageUrl: 'https://i.imgur.com/S2OgjmX.jpeg',
  },
  {
    role: { bn: 'সিটি ক্লিনার', en: 'City Cleaner', ar: 'عامل نظافة مدينة' },
    company: { bn: 'আল তুর্কি কোম্পানী', en: 'Al Turki Company', ar: 'شركة التركي' },
    destination: { bn: 'সৌদি আরব', en: 'Saudi Arabia', ar: 'المملكة العربية السعودية' },
    quantity: 50,
    salary: { bn: '৬০০ SAR + থাকা', en: '600 SAR + Accommodation', ar: '٦٠٠ ريال سعودي + سكن' },
    imageUrl: 'https://picsum.photos/seed/alturki/400/250',
  },
  {
    role: { bn: 'ফুয়েল ফিলার', en: 'Fuel Filler', ar: 'عامل تعبئة وقود' },
    company: { bn: 'আল এস পেট্রোল পাম্প', en: 'Al S Petrol Pump', ar: 'محطة بترول آل إس' },
    destination: { bn: 'সৌদি আরব', en: 'Saudi Arabia', ar: 'المملكة العربية السعودية' },
    quantity: 25,
    salary: { bn: '১১০০ SAR + থাকা', en: '1100 SAR + Accommodation', ar: '١١٠٠ ريال سعودي + سكن' },
    imageUrl: 'https://picsum.photos/seed/alspetrol/400/250',
  },
  {
    role: { bn: 'সিটি ক্লিনার', en: 'City Cleaner', ar: 'عامل نظافة مدينة' },
    company: { bn: 'শারিকাত মাকায়াজ', en: 'Sharikat Makayaj Co.', ar: 'شركة مكياج' },
    destination: { bn: 'সৌদি আরব', en: 'Saudi Arabia', ar: 'المملكة العربية السعودية' },
    quantity: 100,
    salary: { bn: '৬০০ SAR + থাকা', en: '600 SAR + Accommodation', ar: '٦٠٠ ريال سعودي + سكن' },
    imageUrl: 'https://picsum.photos/seed/makayaj/400/250',
  },
  {
    role: { bn: 'ক্লিনার', en: 'Cleaner', ar: 'عامل نظافة' },
    company: { bn: 'আল মাজন কোম্পানী', en: 'Al Majan Company', ar: 'شركة الماجن' },
    destination: { bn: 'সৌদি আরব', en: 'Saudi Arabia', ar: 'المملكة العربية السعودية' },
    quantity: 80,
    salary: { bn: '৫০০ SAR + থাকা', en: '500 SAR + Accommodation', ar: '٥٠٠ ريال سعودي + سكن' },
    imageUrl: 'https://picsum.photos/seed/almajan/400/250',
  },
  {
    role: { bn: 'ইনডোর/আউটডোর ক্লিনার', en: 'Indoor/Outdoor Cleaner', ar: 'عامل نظافة داخلي/خارجي' },
    company: { bn: 'আল জোরাইসি', en: 'Al Joraisi Co.', ar: 'الجريسي' },
    destination: { bn: 'সৌদি আরব', en: 'Saudi Arabia', ar: 'المملكة العربية السعودية' },
    quantity: 70,
    salary: { bn: '১০০০ SAR + থাকা', en: '1000 SAR + Accommodation', ar: '١٠٠٠ ريال سعودي + سكن' },
    imageUrl: 'https://picsum.photos/seed/aljoraisi/400/250',
  },
  {
    role: { bn: 'ডিশেস ক্লিনার', en: 'Dishes Cleaner', ar: 'عامل غسيل صحون' },
    company: { bn: 'বিন সামার কোম্পানী', en: 'Bin Samar Company', ar: 'شركة بن سمار' },
    destination: { bn: 'সৌদি আরব', en: 'Saudi Arabia', ar: 'المملكة العربية السعودية' },
    quantity: 30,
    salary: { bn: '৮০০ SAR + থাকা ও ২ বেলা খাবার', en: '800 SAR + Accommodation & 2 Meals', ar: '٨٠٠ ريال سعودي + سكن ووجبتان' },
    imageUrl: 'https://picsum.photos/seed/binsamar/400/250',
  },
  {
    role: { bn: 'ম্যান লিফট্‌ অপারেটর', en: 'Man Lift Operator', ar: 'مشغل رافعة أفراد' },
    company: { bn: 'এডভান্স লিজিক', en: 'Advance Logic Co.', ar: 'أدفانس لوجيك' },
    destination: { bn: 'সৌদি আরব', en: 'Saudi Arabia', ar: 'المملكة العربية السعودية' },
    quantity: 15,
    salary: { bn: '১২০০+৩০০ SAR + থাকা', en: '1200+300 SAR + Accommodation', ar: '١٢٠٠+٣٠٠ ريال سعودي + سكن' },
    imageUrl: 'https://picsum.photos/seed/advancelogic/400/250',
  },
  {
    role: { bn: 'গভ. অফিস ক্লিনার', en: 'Govt. Office Cleaner', ar: 'عامل نظافة مكتب حكومي' },
    company: { bn: 'আল-হাসাম', en: 'Al-Hasam Co.', ar: 'الحصام' },
    destination: { bn: 'সৌদি আরব', en: 'Saudi Arabia', ar: 'المملكة العربية السعودية' },
    quantity: 40,
    salary: { bn: '৭০০ SAR + থাকা', en: '700 SAR + Accommodation', ar: '٧٠٠ ريال سعودي + سكن' },
    imageUrl: 'https://picsum.photos/seed/alhasam/400/250',
  },
  {
    role: { bn: 'নির্মাণ শ্রমিক', en: 'Construction Worker', ar: 'عامل بناء' },
    destination: { bn: 'সৌদি আরব', en: 'Saudi Arabia', ar: 'المملكة العربية السعودية' },
    quantity: 300,
    salary: { bn: '১৬০০ SAR + ওভারটাইম', en: '1600 SAR + Overtime', ar: '١٦٠٠ ريال سعودي + اضافي' },
    imageUrl: 'https://picsum.photos/seed/construction/400/250',
  },
  {
    role: { bn: 'সেফটি সুপারভাইজার', en: 'Safety Supervisor', ar: 'مشرف سلامة' },
    destination: { bn: 'কাতার', en: 'Qatar', ar: 'قطر' },
    quantity: 50,
    salary: { bn: '৩২০০ QAR + বাসস্থান', en: '3200 QAR + Accommodation', ar: '٣٢٠٠ ريال قطري + سكن' },
    imageUrl: 'https://picsum.photos/seed/safety/400/250',
  },
  {
    role: { bn: 'নার্স (মহিলা)', en: 'Female Nurse', ar: 'ممرضة' },
    destination: { bn: 'জাপান', en: 'Japan', ar: 'اليابان' },
    quantity: 20,
    salary: { bn: 'আলোচনা সাপেক্ষে (উচ্চ)', en: 'Negotiable (High)', ar: 'قابل للتفاوض (مرتفع)' },
    imageUrl: 'https://picsum.photos/seed/nurse/400/250',
  },
  {
    role: { bn: 'প্ল্যান্টেশন ওয়ার্কার', en: 'Plantation Worker', ar: 'عامل مزارع' },
    destination: { bn: 'মালয়েশিয়া', en: 'Malaysia', ar: 'ماليزيا' },
    quantity: 500,
    salary: { bn: '১৫০০ MYR + থাকা', en: '1500 MYR + Accommodation', ar: '١٥٠٠ رينغيت ماليزي + سكن' },
    imageUrl: 'https://picsum.photos/seed/plantation/400/250',
  },
   {
    role: { bn: 'ক্লিনার', en: 'Cleaner', ar: 'عامل نظافة' },
    destination: { bn: 'কাতার', en: 'Qatar', ar: 'قطر' },
    quantity: 150,
    salary: { bn: '১২০০ QAR + থাকা ও খাওয়া', en: '1200 QAR + Food & Accommodation', ar: '١٢٠٠ ريال قطري + سكن وطعام' },
    imageUrl: 'https://picsum.photos/seed/cleaner/400/250',
  },
   {
    role: { bn: 'ড্রাইভার', en: 'Driver', ar: 'سائق' },
    destination: { bn: 'সৌদি আরব', en: 'Saudi Arabia', ar: 'المملكة العربية السعودية' },
    quantity: 100,
    salary: { bn: '১৮০০ SAR + বাসস্থান', en: '1800 SAR + Accommodation', ar: '١٨٠٠ ريال سعودي + سكن' },
    imageUrl: 'https://picsum.photos/seed/driver/400/250',
  },
];

export const STAFF_MEMBERS: StaffMember[] = [
  {
    name: { bn: 'জুবায়ের হায়দার মজুমদার', en: 'Jubayer Haider Mojumder', ar: 'زبیر حیدر মজুমদার' },
    position: { bn: 'ম্যানেজিং ডিরেক্টর', en: 'Managing Director', ar: 'المدير العام' },
    positionEn: 'MD',
    responsibility: { bn: 'বৈদেশিক চুক্তি ও কৌশলগত দিকনির্দেশনা।', en: 'Foreign contracts and strategic direction.', ar: 'العقود الخارجية والتوجيه الاستراتيجي.' },
    imgPlaceholder: 'MD',
    imageUrl: 'https://i.imgur.com/esJDWhj.jpeg',
  },
  {
    name: { bn: 'নিশো খান', en: 'Nisho Khan', ar: 'نيشو خان' },
    position: { bn: 'জেনারেল ম্যানেজার', en: 'General Manager', ar: 'مدير عام' },
    positionEn: 'GM',
    responsibility: { bn: 'অভ্যন্তরীণ কার্যক্রম ও কর্মী নির্বাচন।', en: 'Internal operations and staff selection.', ar: 'العمليات الداخلية واختيار الموظفين.' },
    imgPlaceholder: 'MGR',
    imageUrl: 'https://i.imgur.com/qIKJTHh.jpeg',
  },
  {
    name: { bn: 'আবুল কালাম আজাদ', en: 'Abul Kalam Azad', ar: 'أبو الكلام آزاد' },
    position: { bn: 'আইটি, ইঞ্জিনিয়ার, এম্বাসী প্রতিনিধী, ম্যানপাওয়ার প্রতিনিধী ও ডাটাবেজ কর্মকর্তা', en: 'IT, Engineer, Embassy & Manpower Representative, Database Officer', ar: 'مسؤول تقنية المعلومات، مهندس، وممثل السفارة والقوى العاملة' },
    positionEn: 'IT',
    responsibility: { bn: 'এম্বাসী ও ম্যানপাওয়ার এর সকল কাজ।', en: 'Handles all Embassy and Manpower related tasks.', ar: 'يتولى جميع المهام المتعلقة بالسفارة والقوى العاملة.' },
    imgPlaceholder: 'IT',
    imageUrl: 'https://i.imgur.com/5xphxtP.jpeg',
  },
  {
    name: { bn: 'মোঃ শাহরিন আহমেদ শিহাত', en: 'Md Shaharin Ahmed Shihat', ar: 'محمد شاهين أحمد شيهات' },
    position: { bn: 'অফিস এক্সিকিউটিভ', en: 'Office Executive', ar: 'تنفيذي مكتب' },
    positionEn: 'OE',
    responsibility: { bn: 'অফিসের প্রশাসনিক কাজ পরিচালনা করেন।', en: 'Handles office administrative tasks.', ar: 'يتولى المهام الإدارية للمكتب.' },
    imgPlaceholder: 'OE',
    imageUrl: 'https://i.imgur.com/hcEmyKo.jpeg',
  },
  {
    name: { bn: 'নাজমুল হাওলাদার', en: 'Najmun Haulader', ar: 'نجمون هولادر' },
    position: { bn: 'অফিস সহকারী', en: 'Office Assistant', ar: 'مساعد مكتب' },
    positionEn: 'OA',
    responsibility: { bn: 'অফিসের সব কাজ।', en: 'General office duties.', ar: 'واجبات المكتب العامة.' },
    imgPlaceholder: 'OA',
    imageUrl: 'https://i.imgur.com/93Ny2Gb.jpeg',
  },
];

export const CLIENT_LOGOS: { name: string; logoUrl: string }[] = [
  { name: 'Almarai', logoUrl: 'https://i.imgur.com/mcRk5BF.jpeg' },
  { name: 'Saudi Aramco', logoUrl: 'https://i.imgur.com/lDw09J0.jpeg' },
  { name: 'Qatar Airways', logoUrl: 'https://i.imgur.com/RuKfjGo.jpeg' },
  { name: 'Emirates', logoUrl: 'https://i.imgur.com/NnPMxdd.jpeg' },
  { name: 'Bin Ghara General Contracting Company', logoUrl: 'https://i.imgur.com/6ha4lwG.jpeg' },
  { name: 'Nesma & Partners', logoUrl: 'https://i.imgur.com/bT8zBND.png' },
  { name: 'Al Majal Alarabi', logoUrl: 'https://i.imgur.com/9DrXAdl.jpeg' },
  { name: 'Binladin Group', logoUrl: 'https://i.imgur.com/t2QI7sn.gif' },
];
